name: cohort-monitoring
channels:
  - conda-forge
dependencies:
  - python=3.12
  - streamlit
  - pip
  - pip:
      - langchain
      - langchain-community
      - langchain-core
      - langchain-chroma
      - langchain-google-genai
      - chromadb
      - google-generativeai
      - pydantic
      - numpy
      - pandas
      - duckdb
      - sqlalchemy
      - requests
      - PyYAML
      - tenacity
      - protobuf
      - pyarrow
      - gitpython
      - pydeck
      - jinja2
      - fastapi
      - tqdm
      - httpx
      - dataclasses-json
      - pydantic-settings
      - httpx-sse
      - uvicorn
      - posthog
      - onnxruntime
      - opentelemetry-api
      - opentelemetry-sdk
      - opentelemetry-exporter-otlp-proto-grpc
      - opentelemetry-instrumentation-fastapi
      - huggingface-hub
      - tokenizers
      - rich
      - marshmallow
      - typing-inspect
      - typing-extensions
      - filetype
      - orjson
      - zstandard
      - coloredlogs
      - durationpy
      - requests-oauthlib
      - humanfriendly
      - pyreadline3
      - shellingham
      - watchfiles
      - websockets
      - markdown-it-py
      - mdurl
      - mpmath
      - fsspec
      - hf-xet
      - pyproject_hooks
      - wrapt
      - annotated-doc
      - asgiref
      - starlette
      - propcache
      - overrides
      - mmh3
      - importlib-resources
      - importlib-metadata
      - build
      - colorama
      - click
      - blinker
      - tornado
      - toml
      - smmap
      - gitdb
      - tqdm
      - protobuf
      - cachetools
      - idna
      - charset_normalizer
      - urllib3
      - certifi
      - attrs
      - jsonschema
      - jsonschema-specifications
      - referencing
      - rpds-py
      - six
      - python-dateutil
      - pytz
      - tzdata
      - MarkupSafe
      - narwhals
      - prince
      - scikit-learn
      - pillow
      - pyasn1
      - pyasn1-modules
      - rsa
      - grpcio
      - grpcio-status
      - proto-plus
      - google-api-core
      - google-auth
      - googleapis-common-protos
      - requests-toolbelt
      - zipp
      - anyio
      - httpcore
      - h11
      - sniffio
      - greenlet
      - annotated-types
      - pydantic-core
      - typing-inspection
      - python-dotenv
      - mypy-extensions
      - flatbuffers
      - coloredlogs
      - sympy
      - filelock
      - typer
      - typer-slim
      - pybase64
      - bcrypt
      - backoff
      - build
      - frozenlist
      - kubernetes
      - huggingface-hub
      - shellingham
      - markdown-it-py
      - mdurl
      - mpmath
      - fsspec
      - hf-xet
      - pyproject_hooks
      - wrapt
      - annotated-doc
      - asgiref
      - starlette
      - propcache
      - overrides
      - mmh3
      - importlib-resources
      - importlib-metadata
      - build
      - colorama
      - click
      - blinker
      - tornado
      - toml
      - smmap
      - gitdb
      - tqdm
      - protobuf
      - cachetools
      - idna
      - charset_normalizer
      - urllib3
      - certifi
      - attrs
      - jsonschema
      - jsonschema-specifications
      - referencing
      - rpds-py
      - six
      - python-dateutil
      - pytz
      - tzdata
      - MarkupSafe
      - narwhals
      - prince
      - scikit-learn
      - pillow
      - pyasn1
      - pyasn1-modules
      - rsa
      - grpcio
      - grpcio-status
      - proto-plus
      - google-api-core
      - google-auth
      - googleapis-common-protos
      - requests-toolbelt
      - zipp
      - anyio
      - httpcore
      - h11
      - sniffio
      - greenlet
      - annotated-types
      - pydantic-core
      - typing-inspection
      - python-dotenv
      - mypy-extensions
      - flatbuffers
      - coloredlogs
      - sympy
      - filelock
      - typer
      - typer-slim
      - pybase64
      - bcrypt
      - backoff
      - build
      - frozenlist
      - kubernetes
